### ISSUE TITLE
Typo in 'Why CouchDB?': contacts instead of contracts

### ISSUE THREAD

**Issue by ddknapik** [oreilly/couchdb-guide#481] opened 2013-02-07 00:01 UTC
http://guide.couchdb.org/draft/why.html#better

_We write software to improve our lives and the lives of others. Usually this involves taking some mundane information - such as **contacts**, invoices, or receipts - and manipulating it using a computer application._

The _contacts_ word doesn't match a context here. It seems that you mistyped _r_.

**Comment by sghill** [comment] 2013-03-03 19:09
Hoping to help out with a pull request, I checked into this issue :)

I think "contacts" (no "r") is what was intended and makes sense after reading through the rest of the section --
1. The next illustration is of a business card (contact) and an invoice
2. From there, business cards are used as examples of real-world documents
3. Address books and contact managers are fairly common examples of how to use frameworks

If everyone agrees, perhaps we can leave it as-is and close the issue?

**Closed as completed** 2018-11-17 12:42 UTC
