### ISSUE TITLE
Comment on "Change Notifications"

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#12] opened 2010-08-07 15:25 UTC
From http://books.couchdb.org/relax/reference/change-notifications

> Networks are a tricky beast and sometimes you don=92t know whether there =
> are no changes coming or your network connection went stale. If you add ano=
> ther query parameter heartbeat=3DN, where N is a number CouchDB will send y=
> ou a newline character each N milliseconds. As long as you are receiving ne=
> w line characters you know there are no new change notifications, but Couch=
> DB is still there ready to send you the next one when it occurs.

Question: why would one care about getting a heartbeat signal under
the polling case.  Shouldn't this paragraph be under the continuous or
long polling cases.  Admittedly, I'm reading this to learn about the
_changes api, so maybe I'm missing something

**Comment by janl** [comment] 2010-08-26 23:30
Dupe of #11.

**Closed as completed by janl** 2010-08-26 23:30 UTC
Labels: comment
