### ISSUE TITLE
Comment on "Clustering"

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#18] opened 2010-08-07 15:27 UTC
From http://books.couchdb.org/relax/reference/clustering

> Using CouchDB at web scale likely requires CouchDB clusters that can be s=
> caled dynamically. Growing sites must continuously add more storage capacit=
> y, so we need a strategy to increase the size of our cluster without taking=
>  it down. Some workloads can result in temporary growth in data size, in wh=
> ich case we=92ll also need a process for shrinking the cluster without an i=
> nterruption in service.

I think diagram(s) or config file examples would be helpful for this
entire section.  The phrase, "A picture is worth a thousand words"
certainly applies here.  IMHO, clustering in a scalable fashion will
be a deciding factor for those considering CouchDB in the enterprise.

**Comment by janl** [comment] 2010-08-26 23:34
Dupe of #16.

**Closed as completed by janl** 2010-08-26 23:34 UTC
Labels: comment
