### ISSUE TITLE
[A Basic Design Document] curl command for uploading design file is wrong.

### ISSUE THREAD

**Issue by Spredzy** [oreilly/couchdb-guide#446] opened 2011-11-25 18:43 UTC
When executing the command made in the book I get this error 

Command:

> curl -vX PUT http://127.0.0.1:5984/basic/_design/example -data-binarymydesign.json

Output:

> {"error":"bad_request","reason":"invalid UTF-8 JSON: <<\"ata-binarytoto.json\">>"}

After some research the exact query (at least for my os Mac OS X 10.6) would look like this

Command:

> curl -vX PUT http://127.0.0.1:5984/basic/_design/example --data-binary @mydesign.json

Output:

> {"ok":true,"id":"_design/example","rev":"1-230141dfa7e07c3dbfef0789bf11773a"}

Note the double dash (--) in front of data-binary, followed by a space  and then an @ to define the file name.
## 

Yanis Guenane

**Comment by ghost** [comment] 2012-06-20 21:29
Also working form OSX10.6 and have the same issue. The fixed command works for me. Thanks!

**Comment by sghill** [comment] 2013-03-03 19:23
I think this, and open issue #448, can be closed as a duplicate of resolved issues #415, #422, #428.

The error was fixed in the draft version with commit [b3610d](https://github.com/oreilly/couchdb-guide/commit/b3610d41fcf678eac5726be7fc5f7e97173f07c7)

**Closed as completed** 2018-06-01 07:16 UTC
